"""The browse surface: /browse, /movie/{id}, /movie/{id}/similar, /person/{id}.

Why these exist at all: `POST /chat` answers a question, but a browse page has to
render before anyone has asked one, and a detail modal needs credits — cast,
characters, directors, runtime — that the agent never carries because it never
needed them to write a grounded paragraph. Neither is reachable through the
agent, so the frontend in contract §9 needs a read path of its own.

These are deliberately NOT agent calls. There is no LLM here, no embedding of
user text, no intent routing — just named queries against the two stores. That
keeps the browse page free and instant, and keeps the interesting, expensive,
fallible path (the agent) confined to the endpoint that actually needs it.

Degradation follows the same rule as everywhere else (contract §5): a store being
down produces a thin answer flagged `degraded`, not a 500. A 404 means the film
or person genuinely is not in the catalogue, which is a different fact and the UI
must be able to tell them apart.
"""

from __future__ import annotations

import random
from datetime import date

from fastapi import APIRouter, HTTPException, Query

from core.logger import get_logger
from server.schemas import (
    BrowseResponse,
    BrowseRow,
    Credit,
    MovieCard,
    MovieDetail,
    PersonResponse,
    SimilarResponse,
)

log = get_logger("catalog_api")
router = APIRouter(prefix="/api/v1")

# Films per browse row. Twenty is roughly four screens of horizontal scroll —
# enough that the row never runs out under the cursor, few enough that six rows
# is one response and not one megabyte.
ROW_SIZE = 20

# A quality floor for browse rows only — the agent applies none, because a user
# who asks for a specific film should get it whatever it scores.
#
# TMDB popularity spikes hard around a release, so straight popularity ordering
# opens several shelves with unreleased titles rated 3/10. 6.0 is low enough to
# keep almost everything (the well-rated genres are unchanged by it) and high
# enough to keep those off the landing page.
ROW_MIN_RATING = 6.0

# Genres that are real TMDB categories but not shelves anyone browses. "TV Movie"
# is a production format, so "Because you like TV Movie" is both ungrammatical
# and meaningless. Excluded from the landing page only — the agent still routes
# to them, and a film keeps the genre on its detail page.
NON_BROWSE_GENRES = {"TV Movie"}

# Slides in the hero carousel. Six is one per genre row, so the banner tours the
# whole shelf rather than showing six films from the same corner of it.
HERO_COUNT = 6

# How far down each row a hero may be drawn from. Ten keeps the pool to films
# the catalogue is genuinely surfacing, while leaving rating room to choose.
HERO_POOL = 10

# Row headings. A row called "Drama" reads like a database dump; these read like
# a shelf. Kept here rather than generated by an LLM because a heading that is
# occasionally wrong is worse than one that is always plain.
ROW_TITLES = [
    "Popular in {genre}",
    "{genre} picks for you",
    "Top-rated {genre}",
    "Because you like {genre}",
    "Trending in {genre}",
    "More {genre} to explore",
]


def _card(row: dict) -> MovieCard:
    """Store row -> poster tile. Every field here is already in the query result,
    so a card costs no extra round trip."""
    return MovieCard(
        tmdb_id=row["tmdb_id"],
        title=row["title"],
        year=row.get("year"),
        rating=row.get("rating"),
        poster_path=row.get("poster_path"),
        backdrop_path=row.get("backdrop_path"),
        overview=row.get("overview") or None,
        genres=row.get("genres") or [],
        character=row.get("character"),
    )


@router.get("/browse", response_model=BrowseResponse)
def browse(
    rows: int = Query(default=6, ge=1, le=12),
    seed: int | None = Query(default=None, description="Fixes which genres appear."),
) -> BrowseResponse:
    """Genre rows for the landing page, plus a hero pick.

    `seed` defaults to today's date, so the shelf is stable for a whole session
    (and a whole day) but is not the same six genres forever. Passing an explicit
    seed makes the response reproducible, which is what the tests rely on.
    """
    from agent import catalog

    rng = random.Random(seed if seed is not None else int(date.today().strftime("%Y%m%d")))

    try:
        from stores import neo4j_client

        available = [g for g in catalog.genres() if g not in NON_BROWSE_GENRES]
    except Exception as exc:  # noqa: BLE001
        # No graph, no rows. Reported as degraded rather than empty: the UI shows
        # "some data was unavailable", not "there are no films".
        log.warning("browse_unavailable", error=type(exc).__name__)
        return BrowseResponse(degraded=True)

    rng.shuffle(available)
    chosen = available[:rows]

    built: list[BrowseRow] = []
    degraded = False

    for index, genre in enumerate(chosen):
        try:
            films = neo4j_client.search_movies(
                genres=[genre], min_rating=ROW_MIN_RATING, limit=ROW_SIZE
            )
        except Exception as exc:  # noqa: BLE001
            # One row failing must not lose the five that worked.
            log.warning("browse_row_failed", genre=genre, error=type(exc).__name__)
            degraded = True
            continue

        if not films:
            continue

        built.append(
            BrowseRow(
                title=ROW_TITLES[index % len(ROW_TITLES)].format(genre=genre),
                genre=genre,
                films=[_card(f) for f in films],
            )
        )

    log.info("browse", rows=len(built), degraded=degraded)
    return BrowseResponse(heroes=_pick_heroes(built), rows=built, degraded=degraded)


def _pick_heroes(rows: list[BrowseRow]) -> list[MovieCard]:
    """The carousel: one film per row first, then fill from what is left.

    Taking the leading film from each row before taking a second from any row is
    what makes the carousel feel like a tour of the catalogue. Draining the first
    row would open the page with six films of one genre, which is a worse advert
    for a recommender than any single banner.

    Only films with a backdrop are eligible, and a film already chosen is never
    shown twice — the same title can legitimately appear in two genre rows.
    """
    chosen: list[MovieCard] = []
    seen: set[int] = set()

    # Two passes over the same data: the first takes at most one film per row,
    # the second tops up from whatever remains.
    for take_per_row in (1, HERO_COUNT):
        for row in rows:
            taken = 0
            for film in _hero_order(row.films):
                if len(chosen) >= HERO_COUNT:
                    return chosen
                if taken >= take_per_row or film.tmdb_id in seen or not film.backdrop_path:
                    continue
                chosen.append(film)
                seen.add(film.tmdb_id)
                taken += 1

    return chosen


def _hero_order(films: list[MovieCard]) -> list[MovieCard]:
    """Best-rated of the most popular — not simply the most popular.

    Rows arrive sorted by TMDB popularity, which spikes hard around a release
    date. Taking each row's first film therefore fills the banner with unreleased
    titles carrying a handful of votes: technically the most talked-about films
    in the catalogue, and a poor advert for it.

    Re-sorting the whole row by rating instead would swing too far the other way
    and surface obscure highly-rated oddities. So the candidate pool stays the
    popular head of the row, and rating only decides the order within it.
    """
    return sorted(films[:HERO_POOL], key=lambda f: f.rating or 0, reverse=True)


@router.get("/movie/{tmdb_id}", response_model=MovieDetail)
def movie(tmdb_id: int) -> MovieDetail:
    """Everything the detail modal renders, in one graph query."""
    try:
        from stores import neo4j_client

        detail = neo4j_client.movie_detail(tmdb_id)
    except Exception as exc:  # noqa: BLE001
        log.warning("movie_detail_unavailable", tmdb_id=tmdb_id, error=type(exc).__name__)
        # Unlike browse, there is no partial answer to give here: a modal with no
        # title is not a degraded modal, it is a broken one. 503 lets the client
        # retry, where a 404 would wrongly tell it the film does not exist.
        raise HTTPException(status_code=503, detail="Catalogue is unavailable.") from exc

    if detail is None:
        raise HTTPException(status_code=404, detail=f"No film with tmdb_id {tmdb_id}.")

    return MovieDetail(
        tmdb_id=detail["tmdb_id"],
        title=detail["title"],
        year=detail.get("year"),
        overview=detail.get("overview") or None,
        tagline=detail.get("tagline") or None,
        rating=detail.get("rating"),
        runtime=detail.get("runtime"),
        release_date=detail.get("release_date"),
        poster_path=detail.get("poster_path"),
        backdrop_path=detail.get("backdrop_path"),
        genres=detail.get("genres") or [],
        keywords=detail.get("keywords") or [],
        cast=[Credit(**{k: c[k] for k in ("person_id", "name", "character") if k in c})
              for c in detail.get("cast") or []],
        directors=[Credit(person_id=d["person_id"], name=d["name"])
                   for d in detail.get("directors") or []],
        collection_id=detail.get("collection_id"),
        collection_name=detail.get("collection_name"),
    )


@router.get("/movie/{tmdb_id}/similar", response_model=SimilarResponse)
def similar(tmdb_id: int, limit: int = Query(default=12, ge=1, le=30)) -> SimilarResponse:
    """"More Like This" — vector neighbours, plus the franchise if there is one.

    Both stores are asked independently and either may fail alone: a film with no
    Neo4j is still worth showing neighbours for, and vice versa.
    """
    from server.schemas import FranchiseFilm, FranchiseTimeline

    films: list[MovieCard] = []
    timeline: FranchiseTimeline | None = None
    degraded = False

    try:
        from stores import qdrant_client

        films = [_card(row) for row in qdrant_client.similar_to(tmdb_id, limit=limit)]
    except Exception as exc:  # noqa: BLE001
        log.warning("similar_vector_failed", tmdb_id=tmdb_id, error=type(exc).__name__)
        degraded = True

    try:
        from stores import neo4j_client

        rows = neo4j_client.franchise_timeline(tmdb_id)
        if rows:
            timeline = FranchiseTimeline(
                collection_id=rows[0].get("collection_id"),
                collection_name=rows[0].get("collection_name"),
                films=[
                    FranchiseFilm(
                        tmdb_id=r["tmdb_id"],
                        title=r["title"],
                        year=r.get("year"),
                        is_seed=bool(r.get("is_seed")),
                        poster_path=r.get("poster_path"),
                    )
                    for r in rows
                ],
            )
    except Exception as exc:  # noqa: BLE001
        log.warning("similar_graph_failed", tmdb_id=tmdb_id, error=type(exc).__name__)
        degraded = True

    log.info("similar", tmdb_id=tmdb_id, neighbours=len(films),
             franchise=bool(timeline), degraded=degraded)
    return SimilarResponse(films=films, franchise=timeline, degraded=degraded)


@router.get("/person/{person_id}", response_model=PersonResponse)
def person(person_id: int) -> PersonResponse:
    """A person's filmography, addressed by TMDB person id.

    The id, not the name, is the address — see contract §11 decision #1. Clicking
    "Michael Byrne" in a cast list must show that Michael Byrne's films, not the
    union of every actor who shares the name.
    """
    try:
        from stores import neo4j_client

        profile = neo4j_client.person_profile(person_id)
    except Exception as exc:  # noqa: BLE001
        log.warning("person_unavailable", person_id=person_id, error=type(exc).__name__)
        raise HTTPException(status_code=503, detail="Catalogue is unavailable.") from exc

    if profile is None:
        raise HTTPException(status_code=404, detail=f"No person with id {person_id}.")

    return PersonResponse(
        person_id=profile["person_id"],
        name=profile["name"],
        acted=[_card(m) for m in profile.get("acted") or []],
        directed=[_card(m) for m in profile.get("directed") or []],
    )
